### ISSUE TITLE
Расширить интерфейс IKeyboard

### ISSUE THREAD

**Issue by skyline-gleb** [2gis/Winium.Cruciatus#35]
Методами ЗажатьКнопку, ОтжатьКнопку. Только необходимо определится в терминологии.. KeyDown/KeyUp или PressKey/ReleaseKey
У симулятора SendKeys невозможно реализовать данные методы, поэтому там будет NonImplementedException

**Comment by CSharpRU** [comment]
KeyDown/KeyUp?

**Comment by CSharpRU** [comment]
https://github.com/2gis/Winium.Cruciatus/pull/34
