### ISSUE TITLE
FindElementByName does not identify all the elements with 'same name' under the tree

### ISSUE THREAD

**Issue by SharonJacob** [2gis/Winium.Cruciatus#66]
Hi I'm using Winium to test my application. The application has a navigation tab nad 4 elements witht he name "Worklists". One of them has the Control type button.
I used FindElement(By.Name("Worklists").AndType(ControlType.Button)) but, failed to identify the element.

I also used FindElementsByName("Worklists"). This line only captures the first three elemets and not the button.

Any idea how to navigate to the button element??

Below is the tree structure, worklist button attributes and snippet of C# code

![worklist](https://cloud.githubusercontent.com/assets/22199830/22759054/14ce30c4-ee1f-11e6-9411-97321b6f1059.png)

![worklistbutton](https://cloud.githubusercontent.com/assets/22199830/22759280/d7fa4cc2-ee1f-11e6-93b5-3c1737be0212.png)

![c snippet](https://cloud.githubusercontent.com/assets/22199830/22759303/f0e5f16e-ee1f-11e6-8bf0-c82a431d7605.png)

**Comment by padmaja2812** [comment]
If you check the code for winium it just finds the 1st concurrence of the element by Name.
You can try byID if you have unique id's for your controls.

**Comment by SharonJacob** [comment]
resolved
